name: assets-sync
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: sync
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            at-wat/hokuyo3d
            at-wat/mcl_3dl
            at-wat/mcl_3dl_msgs
            at-wat/neonavigation
            at-wat/neonavigation_msgs
            at-wat/neonavigation_rviz_plugins
            openspur/yp-spur
            openspur/ypspur_ros
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
