name: assets-sync
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: sync
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            at-wat/hokuyo3d
            at-wat/mcl_3dl
            at-wat/mcl_3dl_msgs
            at-wat/neonavigation
            at-wat/neonavigation_msgs
            at-wat/neonavigation_rviz_plugins
            openspur/ypspur_ros
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
      - name: sync bloom release actions
        uses: at-wat/assets-sync-action@v0
        with:
          repos: |
            openspur/yp-spur
          exclude_paths: |
            .github/Dockerfile
            .github/*.sample
            .github/*.sh
            .github/workflows/hide-old-bot-comments.yml
            .github/workflows/prerelease.yaml
            .github/workflows/release-candidate.yml
            .github/workflows/test.yaml
          git_user: Atsushi Watanabe
          git_email: atsushi.w@ieee.org
          github_token: ${{ secrets.GITHUB_TOKEN_REPO }}
